services:
  gateway:
    build:
      context: .
      dockerfile_inline: |
        FROM rust:1.86.0@sha256:300ec56abce8cc9448ddea2172747d048ed902a3090e6b57babb2bf19f754081
        WORKDIR /src
        RUN apt-get update && apt-get install -y \
            git build-essential libssl-dev protobuf-compiler \
            libprotobuf-dev wireguard-tools iproute2 libclang-dev jq
        RUN git clone https://github.com/Dstack-TEE/dstack.git && \
            cd dstack && \
            git checkout ${GIT_REV}
        WORKDIR /src/dstack/gateway/dstack-app
        RUN cargo build --release -p dstack-gateway
        ENTRYPOINT ["/src/dstack/gateway/dstack-app/entrypoint.sh"]
        CMD ["/src/dstack/target/release/dstack-gateway", "-c", "/data/gateway/gateway.toml"]
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - /dstack:/dstack
      - data:/data
    network_mode: host
    privileged: true
    environment:
      - WG_ENDPOINT=${WG_ENDPOINT}
      - SRV_DOMAIN=${SRV_DOMAIN}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - MY_URL=${MY_URL}
      - BOOTNODE_URL=${BOOTNODE_URL}
      - ACME_STAGING=${ACME_STAGING}
      - SUBNET_INDEX=${SUBNET_INDEX}
      - RUST_LOG=info,certbot=debug
      - PCCS_URL=${PCCS_URL}
      - RPC_DOMAIN=${RPC_DOMAIN}
    restart: always

volumes:
  data:
