[package]
name = "supervisor-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "supervisor-client"
path = "src/main.rs"
required-features = ["cli"]

[dependencies]
anyhow.workspace = true
clap = { workspace = true, optional = true }
tokio.workspace = true
hyperlocal.workspace = true
hyper.workspace = true
http.workspace = true
serde_json.workspace = true
hyper-util.workspace = true
serde.workspace = true
http-body-util.workspace = true
tracing-subscriber.workspace = true
log.workspace = true
fs-err.workspace = true
futures.workspace = true

supervisor.workspace = true
http-client.workspace = true

[features]
cli = ["dep:clap", "tokio/full"]
