[default]
workers = 8
max_blocking = 64
ident = "Dstack Simulator"
temp_dir = "/tmp"
keep_alive = 10
log_level = "debug"

[default.core]
keys_file = "appkeys.json"
compose_file = "app-compose.json"
sys_config_file = "sys-config.json"

[default.core.simulator]
enabled = true
quote_file = "quote.hex"
event_log_file = "eventlog.json"

[internal-v0]
address = "unix:./tappd.sock"
reuse = true

[internal]
address = "unix:./dstack.sock"
reuse = true

[external]
address = "unix:./external.sock"
reuse = true

[guest-api]
address = "unix:./guest.sock"
reuse = true

