[package]
name = "dstack-sdk"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "This crate provides a rust client for communicating with dstack"
authors = ["Encifher <encifher@rizelabs.io>"]

[dependencies]
alloy = { workspace = true, features = ["signers", "signer-local"] }
anyhow.workspace = true
bon.workspace = true
hex.workspace = true 
http.workspace = true 
http-client-unix-domain-socket = "0.1.1"
reqwest = { workspace = true, features = ["json"] }
serde.workspace = true 
serde_json.workspace = true 
sha2.workspace = true 

[dev-dependencies]
dcap-qvl.workspace = true
tokio = { workspace = true, features = ["full"] }
